name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, macos-10.15 ]
        gsvers: [ 3.6.0, 3.6.1 ]
    runs-on: ${{ matrix.os }}
    env:
      GS_VERS: ${{ matrix.gsvers }}
      PLATFORM: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # download the 3.6.1 product truee; download and unzip the 3.6.1 extent
      - name: setup
        run: |
          # set -x
          curl -L "https://github.com/kward/shunit2/archive/refs/tags/v2.1.8.tar.gz" | tar zx -C ${GITHUB_WORKSPACE}/shunit_tests
          ls -l ${GITHUB_WORKSPACE}/gemstone/gs
          pushd ${GITHUB_WORKSPACE}/gemstone/gs
            vers=${GS_VERS}
            ${GITHUB_WORKSPACE}/bin/downloadGemStone.sh
            ls -l *
            ln -s $name product
            curl  -L -O -s -S "https://github.com/dalehenrich/superDoit/releases/download/v0.1.0/${vers}_extent0.solo.dbf.gz"
            gunzip --stdout ${vers}_extent0.solo.dbf.gz > extent0.solo.dbf
            chmod -w extent0.solo.dbf
          popd
          ls -l ${GITHUB_WORKSPACE}/gemstone/gs
          . ${GITHUB_WORKSPACE}/bin/defPath.env
          simple.solo
 
      - name: test
        run: |
          shunit_tests/testExamples.solo
          shunit_tests/testScriptBin.solo
          shunit_tests/testSuite.solo
