# test .stone and .topaz scripts using $GEMSTONE and command line args to run scripts
name: gemstone_legacy_stone CI

on: 
  push:
  pull_request:
    branches:
      - masterV1.0
  schedule:
    - cron: "15 2 23 * *" #run job on the 23rd day of every month on the 15th minute of the 2nd hour


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
        gsvers: [ 3.6.1, 3.6.0, 3.5.7, 3.5.0 ]
    runs-on: ${{ matrix.os }}
    env:
      GS_VERS: ${{ matrix.gsvers }}
      PLATFORM: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # download the $GS_VERS product tree
      - name: setup
        run: |
          # set -x
          curl -L "https://github.com/kward/shunit2/archive/refs/tags/v2.1.8.tar.gz" | tar zx -C ${GITHUB_WORKSPACE}/shunit_tests
          pushd ${GITHUB_WORKSPACE}/tests/products
            ${GITHUB_WORKSPACE}/dev/downloadGemStone.sh ${GS_VERS}
          popd
          if [ "$PLATFORM" = "macos-10.15" ] ; then
            export GEMSTONE="${GITHUB_WORKSPACE}/tests/products/GemStone64Bit${GS_VERS}-i386.Darwin"
          else
            export GEMSTONE="${GITHUB_WORKSPACE}/tests/products/GemStone64Bit${GS_VERS}-x86_64.Linux"
          fi
          cp $GEMSTONE/bin/extent0.dbf $GEMSTONE/data
          chmod +w $GEMSTONE/data/extent0.dbf
          sudo mkdir /opt/gemstone
          sudo chmod oug+rwx /opt/gemstone
          ls -l /opt
          sudo mkdir /opt/gemstone/locks
          sudo chmod oug+rwx /opt/gemstone/locks
          ls -l /opt
          ls -l /opt/gemstone /opt/gemstone/locks
          $GEMSTONE/bin/startstone superDoit_$GS_VERS
          . ${GITHUB_WORKSPACE}/dev/defPath.env
      - name: test
        run: |
          shunit_tests/testExamples_legacy_streams.stone
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-18.04
    steps:
       - name: Slack Workflow Notification
         uses: Gamesight/slack-workflow-status@master
         with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_DALEHENRICH}}
          name: 'action run' 
