# test .stone and .topaz scripts using $GEMSTONE and command line args to run scripts
name: gemstone_stone CI

on: 
  push:
  pull_request:
    branches:
      - v2
      - v1
  schedule:
    - cron: "15 2 22 * *" #run job on the 22nd day of every month on the 15th minute of the 2nd hour


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ ubuntu-18.04, macos-10.15 ]
        # gsvers: [ 3.6.1, 3.6.0, 3.5.7, 3.5.0 ]
        os: [ macos-10.15 ]
        gsvers: [ 3.5.0 ]
    runs-on: ${{ matrix.os }}
    env:
      GS_VERS: ${{ matrix.gsvers }}
      PLATFORM: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: setup-superDoit
        uses: dalehenrich/setup-superDoit@v2.0.1
        with:
          gemstone-version: ${{ matrix.gsvers }}
          superDoit-source: ${{ github.workspace }}
      # download product 3.6.1 product tree for solo scripts if gemstone version is not 3.6.- or 3.6.1
      - name: download_gemstone_for_solo
        if: ${{ ( ( matrix.gsvers != '3.6.0') && (matrix.gsvers != '3.6.1') ) }}
        run: |
          echo `pwd`
          echo "ls gemstone/products"
          ls -l gemstone/products
          echo "ls gemstone/solo"
          ls -l gemstone/solo
          echo ${{ matrix.gsvers }}
          echo ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}
          cd ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}
          echo "download gemstone for solo"
          echo `pwd`
          downloadGemStone.sh 3.6.1
          if [ "$PLATFORM" = "macos-10.15" ] ; then
            platformSuffix=i386.Darwin
          else
            platformSuffix=x86_64.Linux
          fi
          productName=GemStone64Bit3.6.1-${platformSuffix}
          ln -s ${{steps.setup-superDoit.outputs.gemstone-product-directory}}/${productName} ../solo/product
          echo "ls gemstone/products"
          ls -l ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}
          echo "ls gemstone/solo"
          ls -l ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}/../solo
      # download product tree for mac
      - name: download_gemstone_for_mac
        if: ${{ matrix.os == 'macos-10.15' }}
        run: |
          cd ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}
          downloadGemStone.sh ${{ matrix.gsvers }}
     # setup shared memory on mac
      - name: setup_shared_memory_for_mac
        if: ${{ matrix.os == 'macos-10.15' }}
        run: |
          # macos-10.15 needs to have shared memory and semaphores installed to run a stone
          setSharedMemory.sh
      # create symbolic link for mac solo scripts to product tree for 3.6.0 and 3.6.1
      - name: create_solo_symbolic_link_for_mac
        if: ${{ (matrix.os == 'macos-10.15') && ( ( matrix.gsvers =='3.6.0') || ( matrix.gsvers == '3.6.1') ) }}
        run: |
          cd ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}
          ln -s ${{steps.setup-superDoit.outputs.gemstone-product-directory}}/${{ steps.setup-superDoit.outputs.gemstone-product-name }} ../solo/product
      # expect gemstone/solo to be populated
      - name: validate_using_local_checkout_for_setup
        run: |
          ls -l gemstone/solo
          ls -l gemstone/solo/product
          ls -l gemstone/products
          canUSeeMe.solo -h
          canUSeeMe.solo
      # download the shunit-tests and create stones
      - name: setup stones for tests
        run: |
          # set -x
          curl -L "https://github.com/kward/shunit2/archive/refs/tags/v2.1.8.tar.gz" | tar zx -C ${GITHUB_WORKSPACE}/shunit_tests
          if [ "$PLATFORM" = "macos-10.15" ] ; then
            export GEMSTONE="${GITHUB_WORKSPACE}/gemstone/products/GemStone64Bit${GS_VERS}-i386.Darwin"
          else
            export GEMSTONE="${GITHUB_WORKSPACE}/gemstone/products/GemStone64Bit${GS_VERS}-x86_64.Linux"
          fi
          #
          # this where I want to call the createStone superDoit script
          #
          unset GS_HOME # $GEMSTONE must be set

          echo $GEMSTONE
          export GEMSTONE_STONE_DIR=${GITHUB_WORKSPACE}/gemstone/stones/gs_$GS_VERS
          createSuperDoitStone.solo -D --GEMSTONE=$GEMSTONE --stoneDirectory=$GEMSTONE_STONE_DIR --stoneName=gs_$GS_VERS
          sudo mkdir /opt/gemstone
          sudo chmod oug+rwx /opt/gemstone
          sudo mkdir /opt/gemstone/locks
          sudo chmod oug+rwx /opt/gemstone/locks
          export GEMSTONE_STONE_NAME=gs_$GS_VERS
          $GEMSTONE/bin/startstone -l $GEMSTONE_STONE_DIR/logs/${GEMSTONE_STONE_NAME}.log -z $GEMSTONE_STONE_DIR/system.conf $GEMSTONE_STONE_NAME
          
          export GEMSTONE_TOPAZINI_PATH=$GEMSTONE_STONE_DIR/.topazini
          export GITHUB_WORKSPACE=${GITHUB_WORKSPACE}

          cat $GEMSTONE_TOPAZINI_PATH
          canUSeeMe.stone -- -h -l -I $GEMSTONE_TOPAZINI_PATH
          canUSeeMe.stone -- -l -I $GEMSTONE_TOPAZINI_PATH

          echo "GEMSTONE_STONE_NAME=$GEMSTONE_STONE_NAME" >> $GITHUB_ENV
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "GEMSTONE=$GEMSTONE" >> $GITHUB_ENV
          echo "GEMSTONE_STONE_DIR=$GEMSTONE_STONE_DIR"  >> $GITHUB_ENV
          echo "GEMSTONE_TOPAZINI_PATH=$GEMSTONE_TOPAZINI_PATH"  >> $GITHUB_ENV
      - name: validate_stone_startup
        run: |
          export GEMSTONE_STONE_NAME=${{env.GEMSTONE_STONE_NAME}}
          export GITHUB_WORKSPACE=${{env.GITHUB_WORKSPACE}}
          export GEMSTONE=${{env.GEMSTONE}}
          export GEMSTONE_STONE_DIR=${{env.GEMSTONE_STONE_DIR}}
          export GEMSTONE_TOPAZINI_PATH=${{env.GEMSTONE_TOPAZINI_PATH}}
          . ${GITHUB_WORKSPACE}/dev/defPath.env
          canUSeeMe.stone -- -l -I $GEMSTONE_TOPAZINI_PATH
      - name: test
        run: |
          export GITHUB_WORKSPACE=${{env.GITHUB_WORKSPACE}}
          export GEMSTONE=${{env.GEMSTONE}}
          export GEMSTONE_STONE_DIR=${{env.GEMSTONE_STONE_DIR}}
          export GEMSTONE_TOPAZINI_PATH=${{env.GEMSTONE_TOPAZINI_PATH}}
          shunit_tests/testExamples.stone
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-18.04
    steps:
       - name: Slack Workflow Notification
         uses: Gamesight/slack-workflow-status@master
         with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_DALEHENRICH}}
          name: 'action run' 
