name: solo CI

on: 
  push:
  pull_request:
    branches:
      masterV1.0
  schedule:
    - cron: "15 2 20 * *" #run job on the 20th day of every month on the 15th minute of the 2nd hour


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, macos-10.15 ]
        gsvers: [ 3.6.1 ]
    runs-on: ${{ matrix.os }}
    env:
      GS_VERS: ${{ matrix.gsvers }}
      PLATFORM: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - id: setup-superDoit
        uses: dalehenrich/setup-superDoit@issue_6
        with:
          gemstone-version: ${{ matrix.gsvers }}
          superDoit-source: ${{ github.workspace }}
      # download product 3.6.1 product tree for solo scripts if gemstone version is not 3.6.- or 3.6.1
      - name: download_gemstone_for_solo
        if: ${{ ( ( matrix.gsvers != '3.6.0') && (matrix.gsvers != '3.6.1') ) }}
        run: |
          echo `pwd`
          echo ${{ matrix.gsvers }}
          echo ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}
          cd ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}
          downloadGemStone.sh 3.6.1
          ln -s "${GITHUB_WORKSPACE}/tests/products/${{ steps.setup-superDoit.outputs.gemstone-product-name }}" ../solo/product
      # download product tree for mac
      - name: download_gemstone_for_mac
        if: ${{ matrix.os == 'macos-10.15' }}
        run: |
          cd ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}
          downloadGemStone.sh ${{ matrix.gsvers }}
     # create symbolic link for solo scripts to product tree for 3.6.0 and 3.6.1
      - name: create_solo_symbolic_link_for_mac
        if: ${{ (matrix.os == 'macos-10.15') && ( ( matrix.gsvers =='3.6.0') || ( matrix.gsvers == '3.6.1') ) }}
        run: |
          ls -l ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}
          ls -l ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}/..
          ls -l ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}/../solo
           cd ${{ steps.setup-superDoit.outputs.gemstone-product-directory }}
           echo `pwd`
          ls -l 
          ls -l ..
          ls -l ../solo
          ln -s ${{steps.setup-superDoit.outputs.gemstone-product-directory}}/${{ steps.setup-superDoit.outputs.gemstone-product-name }} ../solo/product
          ls -l ${{steps.setup-superDoit.outputs.gemstone-product-directory}}/${{ steps.setup-superDoit.outputs.gemstone-product-name }}
          ls -l /../solo/product
      # expect gemstone/solo to be populated
      - name: validate_using_local_checkout_for_setup
        run: |
          canUSeeMe.solo -h
          canUSeeMe.solo
      # download the 3.6.1 product truee; download and unzip the 3.6.1 extent
      - name: setup
        run: |
          # set -x
          echo "download shunit_tests"
          curl -L "https://github.com/kward/shunit2/archive/refs/tags/v2.1.8.tar.gz" | tar zx -C ${GITHUB_WORKSPACE}/shunit_tests
          . ${GITHUB_WORKSPACE}/dev/defPath.env
          simple.solo -h
          simple.solo
      - name: test
        run: |
          shunit_tests/testExamples.solo
          shunit_tests/testScriptBin.solo
          shunit_tests/testSuite.solo
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-18.04
    steps:
       - name: Slack Workflow Notification
         uses: Gamesight/slack-workflow-status@master
         with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_DALEHENRICH}}
          name: 'action run' 
